### ISSUE TITLE
Constraint: Required Tags Force User To Answer

### ISSUE THREAD

**Issue by hallahan** [AmericanRedCross/OpenMapKitAndroid#17]

**Comment by hallahan** [comment]
Any examples of required tags?

cc/ @dalekunce @PaulUithol

**Comment by PaulUithol** [comment]
Just some random examples? In Uganda, for banks (so on choosing the
`amenity=bank` form) we required the `operator` (official bank entity). For
mobile money agents, the `network`s they could transact on. For ATMs, both
`operator` and `network `. Both `addr:city` and `addr:street` could
probably also be required.
On May 11, 2016 9:35 PM, "Nicholas Hallahan" <notifications@github.com>
wrote:

Any examples of required tags?

cc/ @dalekunce <https://github.com/dalekunce> @PaulUithol
<https://github.com/PaulUithol>

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/AmericanRedCross/OpenMapKitAndroid/issues/17#issuecomment-218565934>

**Comment by hallahan** [comment]
Ah, ok, so that means that required tags are often, but not always, activated __only if__ some other tag is selected, like `amenity=bank`.

**Comment by PaulUithol** [comment]
Hmm, could be. Although using distinct forms to isolate choice values
across forms worked fine for us, and would solve this as well I guess. For
example, we had a different list of possible `network` values when filling
out a mobile money agent form, containing MNOs, and when filling out an
ATM's form, containing Visa, MasterCard etc.

**Comment by dalekunce** [comment]
the constraints are very much a tree based constraint model. If this then that kinda stuff. iD or JOSM ontology may help to understand it. Ideally this will get folded into some yet to be spec'd UI form builder.

**Comment by hallahan** [comment]
To know that a question is required, you'll see this:

![2016-05-20 23 20 49](https://cloud.githubusercontent.com/assets/556367/15444551/e8fb25ee-1ea6-11e6-8572-a2a031f26b6d.png)

**Comment by hallahan** [comment]
And then if all of the required questions aren't answered upon save, I'll have a snackbar tell you about it and bounce you back to a tag you haven't answered.

**Comment by hallahan** [comment]
Done.
