### ISSUE TITLE
Create and Select Nodes (POI Creation)

### ISSUE THREAD

**Issue by mberg** [AmericanRedCross/OpenMapKitAndroid#31]
OMK currently only supports selections of ways.

Ability to select a node for tagging and passing to ODK.

This will enable checkins to villages, schools, waterpoints, etc that are normally just nodes.

**Comment by dalekunce** [comment]
@mberg this is tied to #11

**Comment by hallahan** [comment]
Do we want this high priority or save it for later?

**Comment by dalekunce** [comment]
Let's push this to a later sprint. This is a good self contained piece of work.

**Comment by hallahan** [comment]
I did a comprehensive [code review of the Mapbox Android SDK](https://gist.github.com/hallahan/5074f5ac4e2e298e7ba3) regarding the architecture of drawing markers on the map and collision detection from touch events.

In conclusion, the way that all of this works is not efficient at all, and some sort of spatial index will be needed for the Markers if we are to load any significant data set of OSM POIs. Doing this should be straight forward when referencing the code review. 

Because a lot of work goes into rendering markers and capturing touch events with them, it will be best to improve the SDK itself rather than implementing them from scratch. 

Right now, all of the OSM geometry is put in a QuadTree spatial index, including [standalone nodes (POIs)](https://github.com/AmericanRedCross/openmapkit/blob/b02caae6bcdd645b705b390e455c93dbef53c71f/MapboxAndroidSDK/src/main/java/com/spatialdev/osm/model/JTSModel.java#L246-246). The issue is, this index is referenced for a draw call on the `OSMOverlay`, which does not have marker support. Markers go in an `ItemizedIconOverlay`, which is separate. Right now, all of the items (markers) are referenced from a simple list. 

We could take 1 of 2 approaches:

1. Improve the way markers are indexed in the SDK by putting them in a separate QuadTree that lives in the `ItemizedIconOverlay`.

2. Somehow extend the ItemizedIconOverlay to reference the QuadTree in the OSMModel instead of it's own internal simple list.

The next step is to analyze the implications of both approaches regarding how OpenMapKit's model integrates with the Mapbox Android SDK renderer. We need to know which way is easier and less hacky.

**Comment by hallahan** [comment]
I'm going to move forward with option 2 -- should be more straightforward. Perhaps subclass ItemizedIconOverlay to reference the QuadTree.

**Comment by hallahan** [comment]
Marker placement is not a trivial UX. Taking the typical approach, the user can select and drag around a marker, but on a touch screen, the finger covers the marker--and then you don't see what is happening on the screen...

I've seen two approaches address this problem:

Uber  | Gaia GPS
--------------- | ----------------
![uber-marker](https://cloud.githubusercontent.com/assets/556367/9208229/29914106-4027-11e5-9633-1c968fb0c98e.png) | ![gaia-marker](https://cloud.githubusercontent.com/assets/556367/9208237/31c44c6a-4027-11e5-8c03-6a37b8b4dd06.png)
There is a static marker over the center point of the map. The user moves the map, and the marker is placed in the central cross-hair. | There is a circle around the marker, and the user can drag the marker by touching any point in the circle.

If we take the Uber approach, when the user touches an existing marker, the map pans the marker to be in the center point. The map is in a marker placement mode, and the user pans the map to place the marker.

If we take the Gaia GPS approach, the user touches an existing marker, the marker then gets a circle around the marker. The circle can then be dragged into the new marker location.

Opinions? @dalekunce

**Comment by hallahan** [comment]
Point on Map ®

![2015-08-11 20 20 54](https://cloud.githubusercontent.com/assets/556367/9209556/08380fa8-402c-11e5-8346-04fccfd2b479.png)

**Comment by mberg** [comment]
I personally think the uber approach allows a higher level of precision
once you get used to it.

Try playing around with geodk.  Dropping points is a bit clunky.

Option two works well for point selection but that's obviously a different
route

**Comment by hallahan** [comment]
Agreed. If the map pans marker to center, selection is fine with Uber approach as well.

**Comment by dalekunce** [comment]
Agree with @mberg the uber approach is probably the best.

**Comment by hallahan** [comment]
Getting markers on the map via OSM JTSModel QuadTree.

![2015-08-12 00 02 09](https://cloud.githubusercontent.com/assets/556367/9213798/4433ca5a-404b-11e5-8672-289bbc24cca8.png)

**Comment by hallahan** [comment]
Sorts the markers by latitude so higher markers are covered by lower markers.

![2015-08-12 00 15 23](https://cloud.githubusercontent.com/assets/556367/9213921/ae5d0c06-404c-11e5-969c-9988cf64b4b0.png)

**Comment by mberg** [comment]
Can you drop the icon size too?

On Tue, Aug 11, 2015 at 7:16 PM, Nicholas Hallahan <notifications@github.com

**Comment by hallahan** [comment]
Icons have not yet been delt with. I've gone through the details of the icon glyphs (Maki Markers) in the [code review](https://gist.github.com/hallahan/5074f5ac4e2e298e7ba3). I'm going to look at what the tag is to render the appropriate icon.

**Comment by hallahan** [comment]
[Notes on Marker Selecton](https://gist.github.com/hallahan/5c84c5120cc1e7463f48) showing where the logic to pan the map and show the marker is in the SDK.

**Comment by hallahan** [comment]
Nodes are getting added.

![2015-08-14 21 27 10](https://cloud.githubusercontent.com/assets/556367/9284436/9aa9ea4e-4290-11e5-8480-c86d6bb6b99c.png)

**Comment by hallahan** [comment]
Buttons to Add Tags. Buttons to Delete and Move markers.
![2015-08-18 19 33 27](https://cloud.githubusercontent.com/assets/556367/9340587/6fa892e2-45a5-11e5-8dd7-4ef3e9b28f51.png)

**Comment by hallahan** [comment]
Selecting a marker turns it orange.
![2015-08-19 17 49 57](https://cloud.githubusercontent.com/assets/556367/9364250/3feae828-4660-11e5-9503-b78417e20b41.png)
