### ISSUE TITLE
HXL support

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#41]
add HXL support for tags

**Comment by hallahan** [comment]
So you can just go in and make a tag key hxl:whatever. What are you implying by "support"?

**Comment by dalekunce** [comment]
perfect lets just do some documentation to show this support.

**Comment by hallahan** [comment]
Can we assign someone at Red Cross who is smart with HXL to explain this in a wiki?

**Comment by dalekunce** [comment]
@simonbjohnson would be a great candidate. He is really well versed in HXL I'll ask him.

**Comment by SimonbJohnson** [comment]
"add HXL support for tags"...Not quite grasping the usage.  Is a tag applied to individual data fields?

**Comment by hallahan** [comment]
OpenStreetMap accepts tags for a given map feature. A tag can be any string key value pair. Technically speaking, you can give it arbitrary strings for the keys and values, though this is frowned upon.

Since OpenMapKit is adding tags, we can give it tags that conform to HXL. One example of how this is done can be seen with TIGER imports. Tiger data has it's own fields from the original shapefiles. Some of these fields are turned into OSM Tags. The convention is to have the key be "tiger:someKey" with the value.

Here is an example of the street I live on. This data was originally imported from TIGER, and corresponding tiger fields are tagged in there:

http://www.openstreetmap.org/way/6441407

So, for HXL, you want the keys to be "hxl:someKey"

**Comment by mberg** [comment]
I understand value of hxl in terms of incorporating into the  forms for
reporting. We are adding hxl support to ona as an example.

What's the use case for tags. Not in disagreement but trying to understand
better based on what I understand from hxl.  Ie) are hxl tags something we
want in osm?

**Comment by davidmegginson** [comment]
Thanks for thinking of us! I'm an outsider in this discussion, so I'm going to use the concrete example of a GeoJSON layer and hope that there's enough of a parallel with what you're actually discussing to be useful.  Are you thinking about a way to tag properties for features, something like this?

```{
  type: "Feature",
  properties: {
    "#country": "Guinea",
    "#country+code": "GIN",
    "#adm1": "Nzerekore",
    "#adm1+code": "GIN008",
    "#people_num": 1663582
  },
  geometry: {
    ...
  }
}```

I noticed one mention of prefixing (for namespaces), so maybe it would be more like "hxl:adm1" rather than "#adm1", but in either case, I can see potential benefits in using HXL as a property vocabulary for geographic layers.

**Comment by davidmegginson** [comment]
Also, FYI, we're in the processing of a major reduction in the number of HXL tags, with optional attributes for disambiguation: https://docs.google.com/spreadsheets/d/1b5s_o11e6E0kmaPC3GFYM78rlrNm3_qmDzdevWHk-es/edit?usp=sharing

Here's our tag attribute proposal: https://docs.google.com/document/d/1CM1ej8HKVBMeP-orwVFViTAKtvCZ5c94UrOPbWVdRRc/edit?usp=sharing

**Comment by hallahan** [comment]
Hi @davidmegginson and @mberg. Yes, I do think HXL tags would be a great enrichment to the OSM dataset. David, you are exactly correct with regards to what I am thinking.

@jaakkoh, you are the resident OSM authority. What is your opinion?

**Comment by mberg** [comment]
When we are on this topic.

Are there are any examples of people embedding hypermedia links to external
resources in tags.

Ie) It would be great if we could tag for a health facility in OSM the link
to REST resource for that facillity in DHIS2 or another service that
supports something like the facility registry spec

http://facilityregistry.org/



On Thu, Mar 26, 2015 at 9:14 PM, Nicholas Hallahan <notifications@github.com

**Comment by hallahan** [comment]
Sure! There's tons of wikipedia and other website links links in OSM. 

Link to website for Experience Music Project in Seattle:
http://www.openstreetmap.org/node/366030436

Wikipedia:

http://wiki.openstreetmap.org/wiki/Talk:Key:wikipedia

Here is the Relation for Seattle that has a Wikipedia link to the specific article about Seattle:

http://www.openstreetmap.org/relation/237385

Looking at the XML, the tag is as such:

```xml
<tag k="wikipedia" v="en:Seattle"/>
```

For websites, you get the complete link.
