### ISSUE TITLE
Easy Install Process

### ISSUE THREAD

**Issue by dalekunce** [AmericanRedCross/OpenMapKitAndroid#42]
Install Process shouldn't involve so much dragging of files from a computer. We need a way for OMK to fetch mbtiles and osm data from urls and save to the phone.

**Comment by hallahan** [comment]
The more I think about it, it seems to make the most sense to have a web service pump out an MBTiles for us. Regarding OSM data, it would be straightforward to hit Overpass from the app via HTTP and store the response as an OSM XML file.

**Comment by hallahan** [comment]
If you had OMK fetch PNGs to make an MBTiles, it would be much slower than just have a server bake it for us. 

Then the question is: do we want to dive into this when we want to just switch to vector tiles anyway?

**Comment by dalekunce** [comment]
Ideally we prebake the OSM file and put on a server (s3) so we can download. For right now OMK only needs to fetch the OSM file from a url and put it in the openmapkit folder. Later we can have OMK send a bbox and options from a pick list (buidlings, roads, landuse, etc) to a service to bake the OSM. As you said though, this may all go away once we switch to vector tiles. For me this is a super important issue if we deploy to Venautu in a couple weeks.

**Comment by hallahan** [comment]
We can have a set of Overpass queries hard coded into the app and have associated buttons get us what we want, like buildings. It would be pretty straightforward to post an Overpass query with the map's current bbox to get data for a given area. This should make more sense than S3, because it would guarantee fresh data, and it wouldn't be any more difficult. 

We can come up with an easy plan to meet your OSM XML needs for Venautu. Regarding MBTiles, that's a more involved effort.

**Comment by hallahan** [comment]
This will be addressed as part of the provisioning feature. @dalekunce - Could you add a Provisioning label? I do not have labeling ability in this repo.

**Comment by hallahan** [comment]
This is done via deployments #122. Much much easier now.
