### ISSUE TITLE
numbering system for osm_building value for new POIs?

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitAndroid#97]
If each device follows the same numbering schema for new POIs is the compiled data going to have multiple entries with osm_building = OSMNode-1.osm ?

**Comment by mberg** [comment]
These should probably be time stamped

See:  https://github.com/AmericanRedCross/OpenMapKit/issues/92

**Comment by danbjoseph** [comment]
on one device, the numbering restarted.... after sending completed forms? i don't think i closed out the app at any point.
<img width="592" alt="screen shot 2015-11-15 at 5 05 55 pm" src="https://cloud.githubusercontent.com/assets/4806884/11168484/566adcfc-8bbb-11e5-87fb-d8d72956f1cf.png">

**Comment by mberg** [comment]
Sorry these are for new poi's i got confused.

**Comment by hallahan** [comment]
Negative values are used as a placeholder within a given changeset to uniquely identify a new element. This is how JOSM and iD work.

Since entries are simply concatenated, this is a problem. This would be a responsibility for the server, and this should be an issue on the server repo, not the Android app.

Simply time stamping the name of the files is not going to affect what happens on the OSM api. The API will still get confused by seeing multiple nodes with the same negative ID.

**Comment by hallahan** [comment]
`aggregate-osm.js` takes care of this. Also, we're adding timestamps to file name now. See #92.
