### ISSUE TITLE
delete a POI node option is confusing

### ISSUE THREAD

**Issue by danbjoseph** [AmericanRedCross/OpenMapKitAndroid#99]
- If you create a POI in one form. And then select and delete it when OMK is later open for completing another survey. Does anything more happen than it being removed from the OMK map?
- If you submit data and delete saved/submitted forms. Generated POIs still appear on the OMK map. They are also still deletable. 
- It seems that while filling out one form you can add multiple nodes (and they all persist on the OMK map) but only the one that you step through the tags with and 'Save tag edits to ODK Collect' will be saved into the form and eventually submitted. 
- A user can end up adding a bunch of POIs that show up in OMK but are not actually saved into a form to be submitted?

**Comment by hallahan** [comment]
I agree that this button should be taken out. Originally, I was thinking that one could add multiple POIs per response, however, that doesn't really work right with ODK, since you really do only want one element per OSM response in an ODK form.

Also, you are correct that one can't delete POIs that have already been submitted to the server (obviously).

Also, you are correct that the user can currently add a bunch of POIs that show up, but are not actually __saved to the XForm Instance XML__. They are saved and submitted to the server as media attachments, and this isn't right. This is the cause of bug #115.
